### ISSUE TITLE
Problems with Sf.Graphics.Rect

### ISSUE THREAD

**Issue by HonkiTonk** [mgrojo/ASFML#11]
Hi,

I have some problems with the two functions "contains" in Sf.Graphics.Rect.

After discovering the functions I wanted to replace my own solution with them, but the float variant always returned false and I thought that was a bug. But after writing a short test code (see the Test files) I noticed that the integer variant also returns False but also throws the warning "SFML warning: trying to use a null rect object".

Now I'm a little confused. Is there now an error in the functions or am I making a mistake by passing a record instead of an access?

It happens in the release version 2.5.2 and with a self-compiled version based on the current code.

[Test.adb.txt](https://github.com/mgrojo/ASFML/files/9281807/Test.adb.txt)
[Test.ads.txt](https://github.com/mgrojo/ASFML/files/9281809/Test.ads.txt)

**Comment by mgrojo** [comment]
Hi @HonkiTonk,

It's my fault. I wanted to simplify the interface in this case and avoid the C-ism of passing a pointer to constant, when the Ada interface to C can internally pass the pointer when the parameter is a record and the convention is just "C". Unfortunately, I didn't change the convention, it remained "C_Pass_By_Copy", and none of my tests included those functions.

There are two solutions:
1. Restore the C-ism and change the parameter to "access constant". This is what the API is doing in many other places.
2. Fix the API improvement by changing the "C_Pass_By_Copy" to just "C". In this case, the other similar "access constant" parameters in this package should be also be just sfFloatRect or sfIntRect. They would also work with the C convention, but I reckon it should be changed for homogeneity.

Do you as user has any preference? I'm thinking of choosing 1, so the only API change is in these misbehaving functions.

**Comment by HonkiTonk** [comment]
Personally, I have hardly used Access so far, so the second solution would probably be more suitable for me. However, I usually don't know what I'm doing and I'm happy if it works halfway in the end, so I'm probably not the right person to ask.

**Comment by mgrojo** [comment]
I've finally implemented number 1, because changing the convention to `C` would break other uses of these types in other functions, like `Sf.Graphics.Transform.transformRect`, where the record is passed by copy. I don't understand the rationale in CSFML to pass the record by copy or by constant pointer, but it is safer to follow what CSFML is doing, than trying to simplify the API without a proper test of all the functions.

In fact, I guess I implemented these functions correctly but then, changed back the convention due to problems in other functions, like the one I mentioned. I hope everything works for these types.

You can find usage examples in tests/graphics/main.adb. Usually, it's just a matter of defining the variable as `aliased` and then using `'Access'  to get the access to the variable. Let me know if you have any problem.

Danke für den Bug-Bericht!

**Comment by HonkiTonk** [comment]
Ok, I'll let you know if I encounter any other problems that I can't solve myself.
